### ISSUE TITLE
Watson queryset search fails for some models (Django primary key issue?)

### ISSUE THREAD

**Issue by yrdeboer** [etianen/django-watson#149]
Hi,

I observe that the watson search does not seem to behave well for searches using querysets, however, only for some models of mine ... *please note my question at the bottom of this issue*.

Below my transcript from an ipdb session (django 1.7.11, django-watson 1.2.0), where I would expect identical output, which I don't get:

    ipdb> len(watson.search.search('list', models=(ServiceRequest.objects.all(),)))
    0
    ipdb> len(watson.search.search('list', models=(ServiceRequest,)))
    54

But, for another model of mine, the same construct **does** lead to identical results:

    ipdb> len(watson.search.search('yt', models=(UserProfile.objects.all(),)))
    4
    ipdb> len(watson.search.search('yt', models=(UserProfile,)))
    4

**Furthermore**, when I try to use the "filter" option, I run into the following error:

    ipdb> watson.search.filter(ServiceRequest.objects.all(), 'list')
    *** django.db.utils.ProgrammingError: relation "watson_searchentry" does not exist
    LINE 1: ...."type", "incidents"."urgency" FROM "incidents" , "watson_se...

which I **don't** get using the same construct on my other model:

    ipdb> watson.search.filter(UserProfile.objects.all(), 'greg')
    [<UserProfile: <User Profile: gregor@test.co.nl>>]

Note:

    ipdb> len(ServiceRequest.objects.all())
    3231

**Question**: The primary key of model "ServiceRequest" is *not* the usual "id" field ... could that be a the problem ... if so, how do I best get around that?

Many thanks for any attention to my problem ... 

Ytsen.

**Comment by etianen** [comment]
It sounds like you have a multi-db setup, with ServiceRequest being in a different database to SearchEntry. Is this correct?

**Comment by yrdeboer** [comment]
Keenly deduced Sir indeed!

I deplorably failed to point out that important detail to you.

You are right, that indeed is the case ... am I lost or is there some shimmer of hope?

Kind regard,

Ytsen.

**Comment by etianen** [comment]
The watson.search.filter method relies on a JOIN operation between the two tables, which can't be done between databases. So that approach is doomed.

The watson.search.search method with a queryset specifier relies on a WHERE IN clause, which won't work between databases either. However, for some reason, in this case there's no error from Django or the database, just a silent failure and no results. Not ideal, but this is a Django issue, and not relevant here. Still, the approach is doomed by design.

I guess that leaves watson.search.search with a model specifier, which doesn't rely on any in-database table relations.

I assume you have a damn good reason for keeping things in different databases? I've never understood the point of this, so would be curious to hear a use-case.

**Comment by yrdeboer** [comment]
Thank you for your clear reply and question.

I'll accept my fate and be happy with the watson.search.search method with a model specifier.

Then on the issue of keeping things in different databases: Our second database (with "ServiceRequest" in it from my use case), is a volatile read-only database. Its content is determined by another system and can change at set times.

**Off-topic counter question:** Do you think that is good enough a reason?

**Comment by etianen** [comment]
Personally, I'd keep your two databases together. If you want to enforce
access rights, use two different database users. Two independent
applications can coexist in the same database and share data. :)

Of course, that relies on the devs from both teams being vaguely
cooperative and not stamping all over each other's tables!
