### ISSUE TITLE
Results don't include manytomany keys

### ISSUE THREAD

**Issue by Alphare** [etianen/django-watson#158]
Hi!

I've registered a `UserAccount` class the following way:
```
UserAccount = self.get_model('UserAccount')
watson.register(UserAccount.objects.filter(is_active=True), exclude=("email", "password")) 
```
This `UserAccount` class has a foreignkey to a `Candidate` class. This `Candidate` class itself has a manytomany field to a City class.
When I use `watson.search()`, all `Candidate` instances have empty manytomany fields, even though the actual objects have one or more related objects.

`Candidate` is also registered to watson, with no "exclude" or "include" parameter.

I may not have given you enough information, sorry in advance.

**Comment by etianen** [comment]
This should help:
https://github.com/etianen/django-watson/wiki/Registering-models#searching-across-related-models

**Comment by Alphare** [comment]
I've already used the decorator methods. My result.object is a Candidate class, and its foreignkey/manytomany fields are None. It's like watson doesn't fetch the related objects when doing a search.

**Comment by etianen** [comment]
Try the latest master branch. There's a bug in django's prefetch_related mechanism that keeps biting django-watson, so I've experimentally tried disabling it.

Bear in mind that accessing result.object will incur a database hit for each search result. If you're only searching one model table, consider using watson.filter(Candidate, "search term") instead, which returns a queryset of Candidate rather than SearchResult.
