### ISSUE TITLE
Boolean Search

### ISSUE THREAD

**Issue by timkofu** [etianen/django-watson#165]
Being that PostgreSQL supports Boolean Search, when will it come to Watson?

**Comment by etianen** [comment]
Almost certainly never, since the syntax is database-dependent, and can't
be supported in all search backends.

It would require implementing a new, opt-in boolean search language that
would be then transcompiled to a database-specific boolean search.

I'm open to convincing, but this feels like a lot of complexity to
implement a feature that's not applicable to a lot of users.
