### ISSUE TITLE
Release 1.11 changes

### ISSUE THREAD

**Issue by codingjoe** [etianen/django-watson#208]
Hi @etianen,

How are you doing? I saw that @moggers87 did some work to get watson 1.11 ready.
I wondered if there is any reason why you haven't released those changes yet? In particular this commit: a5b3c7830f6dd3f12634b7860af44d8272b7c07a

BTW, you can setup [Travis-CI PyPi deploys](https://docs.travis-ci.com/user/deployment/pypi/). That way you just have to tag a commit to deploy, I'm using it on my projects too.

Anyways, good week!
-Joe

**Comment by moggers87** [comment]
Those changes are mostly test related, if you're not using the search result template tags then you don't actually need  to wait for a release.

**Comment by etianen** [comment]
It's pretty simple to use a public git repository as a PyPi dependency, if
you want the latest and greatest.

I'm mostly holding off to see if there are any reported consequences of the
multiple database support. It's been a while since that was added, though,
so if there's demand for a release it can be accomplished pretty quickly.

**Comment by etianen** [comment]
I've just released 1.4.0, so there's no need to install from master now. :)

**Comment by codingjoe** [comment]
❤️
