### ISSUE TITLE
Doesn't pick up worded numbers in search terms

### ISSUE THREAD

**Issue by Domchap90** [etianen/django-watson#304]
This may be done intentionally but I have a news article model (Article) which has a title field. I register the article with watson at the bottom of the models.py like so...

watson.register(Article.objects.all(), store=("title", "description", "meta_description"))

I have customised a global search view to allow for django cms Title objects as below

```
      from cms.models import Title
      from watson import search as watson
      from watson.views import SearchView
      
      
      class SearchView(SearchView):
          """
          Overrides django watson search view and returns the search results.
          """
      
          template_name = "watson/search_results.html"
      
          def get_queryset(self):
              results = list(
                  watson.filter(
                      Title.objects.filter(published=True, publisher_is_draft=False),
                      self.query,
                  )
              )
              results += list(watson.search(self.query, models=self.get_models(), exclude=[Title]))
      
              return results
```

Now on my main search page i have setup test articles entitled "Article two" / "Article Three" . Now if i search "article" they get picked up also if the second word is not a spelled number i.e. "example" that will pick up an article entitled "article example" . However query "three" does not pick up "article three".

Why is this ? (if intentional)

**Comment by etianen** [comment]
The implementation of the search depends on the database. I'm gonna assume you're using Postgres here, since that has the most powerful but also the most suprising behaviours.

Basically, your search query is changed / stemmed / pruned based on the search configuration:

https://www.postgresql.org/docs/current/textsearch-dictionaries.html

The `WATSON_POSTGRES_SEARCH_CONFIG` setting allows you to choose the search config to use. The default for `django-watson` is `pg_catalog.english`. You could try using `pg_catalog.simple` and seeing if that affects the results.

After changing this setting, you will need to run:

``` bash
./manage.py uninstallwatson
./manage.py installwatson
./manage.py buildwatson
```
