### ISSUE TITLE
Retrieving ordered results (order_by)

### ISSUE THREAD

**Issue by marcelosalloum** [etianen/django-watson#35]
Hello guys,

Is that possible to retrieve results from the watson search that are already ordered by a given attribute? For example, I'd like to retrieve the Publication model always ordered by date and the Writer model always ordered by name.

Is it possible to define the order in the register step?

I am trying to order the results, unsuccessfully, in the following way: 
watson.search("Search terms", models=(Writer.objects.filter(name="foo").order_by("name",))

Is there a built in way to order the results? If this is a feature that needs to be implemented, Could you give me the guidelines?

Cheers,

**Comment by cho-is** [comment]
so are you saying it is not possible to order_by watson.search() multiple models?

**Comment by etianen** [comment]
Unfortunately, database joins don't really permit that, as it's not the same field from the database's point of view.

If all your models inherited from the same base (non-abstract) model, it might be possible, but otherwise it's just not something SQL really supports without substantial hackery (and big performance problems)

**Comment by acquayefrank** [comment]
@etianen What If I'm using a single model and I've added the order_by to my Meta description. Would that suffice

**Comment by etianen** [comment]
This is an SQL limitation, really, not a Django one. The filter() method works on a single model, and permits custom filtering and ordering. The search() method works on multiple models, and does not permit custom filtering and ordering.

**Comment by acquayefrank** [comment]
I have no problem with the multiple models/single models. I've  registered my model and everything works fine.
Let me describe my issue. 
I need to search through a bunch of restaurants..... So say  a user searches for Lobster. "The Red Lobster" shows up first because of the name. Second is Kao-Lee because of the description. But I would rather Kao-Lee shows first due to better reviews.

**Comment by etianen** [comment]
The filter() methods returns a queryset of your model. You can do whatever
you want with it.

watson.filter(Restaurent, "Lobster",
ranking=False).order_by("-review_score")
